name: trip_script
description: "My Final Year Project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  provider: ^6.1.2
  cloud_firestore: ^4.14.0
  uuid: ^4.4.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  webview_flutter: ^4.8.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - images/
    - icons/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
